ONLYOFFICE/documents-app-android

app_manager/appmanager/src/main/java/app/editors/manager/app/Api.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/receivers/UploadReceiver.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/services/UploadService.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/NewNotificationUtils.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/works/UploadWork.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/main/MainActivity.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/UploadFileViewHolder.java
Загрузка файлов осуществляется через WorkManager. При потере соеднинения с Интернетом и последующем восстановлении соединения загрузка возобновляется
=> Rework upload files

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Исправлена ошибка при попытке скачать папку
=> Fixed bug when try to download folder caused "Access denied"

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsBaseView.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsRecentView.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.java
Added reverse sort order after repeated tap on sort category
=> [android][appmanager] fix bug #43345

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/BaseLoginPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/EnterprisePortalPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/MainPagerFragment.java
Now Favorites are supporting on portals with version 11 and more.
=> Favorites are supported correctly

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.java
Now there is progress dialog while trash is being cleared
=> [android][appmanager] fix bug #48681

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.java
Added snackbar to notify user about change access rights in Recent
=> [android][appmanager] fix bug #48860

app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/main/MainActivity.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/CloudAccountsFragment.java
Unlock bottom navigation panel after tap Remove/Cancel button in dialog in Cloud Account section
=> Unlock bottom nav in Cloud Account tab

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Now getting correct file status when file is opened on portal and simultaneously added in Favorites
=> correct file status when file deleting

app_manager/appmanager/src/main/java/app/editors/manager/app/Api.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/receivers/DownloadReceiver.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/NewNotificationUtils.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/works/DownloadWork.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java, app_manager/appmanager/src/main/res/values-ru/translatable.xml, app_manager/appmanager/src/main/res/values/translatable.xml
Archiving progress, error handling for server messages were added. Archive extension was changed according to server
=> Fix bug 48600

toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/activities/base/BaseActivity.kt
Close waiting dialog if URL is not correct in NextCloud connect activity
=> [android][appmanager] fix bug #45654

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Removing files from On Device section is doing correct now
=> [android][appmanager] Fix bug #49010

app_manager/appmanager/src/main/java/app/editors/manager/di/component/AppComponent.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/EnterpriseSSOPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/login/EnterpriseSSOView.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/login/EnterpriseSignInFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/login/SSOLoginFragment.java, app_manager/appmanager/src/main/res/layout/sso_login_layout.xml, app_manager/appmanager/src/main/res/values/translatable.xml
=> [android][appmanager] Added SSO authorization

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/AccountsPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/EnterpriseLoginPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/CloudAccountsPresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/CloudAccountsFragment.java
Fixed bug connected with 2fa and account list
=> [android][appmanager] Fixed bug #49027

toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/dialogs/common/CommonDialog.kt
Changing orientation does not crash application
=> [android][appmanager] Fixed bug #49577

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsWebDavFragment.java, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/dialogs/common/holders/EditLineHolder.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/dialogs/common/holders/QuestionHolder.kt
Removing file from Clouds (e.g. Nextcloud, Owncloud etc.) is working correctly now
=> Fix bug 50419

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.java
Toolbar draw correctly in recent section after change orientation of device
=> [android][appmanager]Fixed bug #50643

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.java
Close button in search in Recent section is working now
=> [android][appmanager] Fixed bug #50703

app_manager/appmanager/src/main/java/app/editors/manager/mvp/models/ui/ShareUi.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/share/SettingsView.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/SettingsFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/popup/SharePopup.java
Popup in Share for Guest has "Read only" and "Deny access" now
=> [android][appmanager] Fixed bug 50689

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/SettingsFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/popup/SharePopup.java, app_manager/appmanager/src/main/res/layout/popup_share_menu.xml, app_manager/appmanager/src/main/res/values/translatable.xml
Can remove user from list of shared now
=> [android][appmanager] Fixed bug 51546

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsTrashFragment.kt
Items in Trash section refresh after change orientation
=> [android][appmanager] Fixed bug #51766

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/StorageUtils.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/core/src/main/java/app/documents/core/network/ApiContract.kt
Storage icon in context bottom dialog matches with connected storage
=> [android][appmanager] Fixed bug #51765

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/UiUtils.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.java
The document icon in bottom context menu is colored now
=> [android] Fix bug 51763

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt
It's displayed correctly when deleting the last document
=> [android] Fix bug 51879

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt
Fixed bug when placeholder in share settings was not displayed when there are no users
=> [android] Fix bug placeholder in share settings

app_manager/appmanager/src/main/java/app/editors/manager/managers/receivers/DownloadReceiver.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/NewNotificationUtils.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/NotificationUtils.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/works/DownloadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsBaseView.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.java, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/ActivitiesUtils.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/fragments/base/BaseFragment.kt
Fixed bug when the download folder was not opened correctly
=> [android] Fix bug 51295

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt
When deleting a document from the "Shared with me" section, it was not deleted correctly.
=> [android] Fix bug 51980

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCloudFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCommonFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsFavoritesFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsMyFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsProjectsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsShareFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsTrashFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/MainPagerFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/operations/DocsCloudOperationFragment.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/pager/ViewPagerAdapter.java
Fixed bug when the add button was displayed after rotating the screen.
=> [android] Fix bug 51860

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/MainPagerFragment.kt
Switch on/off Favorite section on portal is updated correctly now
=> [android][appmanager] Fixed bug #52009

app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/ExplorerAdapter.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt
Placeholder appears correctly when deleting files on device
=> [android] Fix bug 42753

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsOnDeviceView.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt
Local media files open correctly now
=> [android] Fix bug 51774

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.kt
Fixed bug when removed files were opened in the recent.
=> [android] Fix bug 52221

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.java
Share function in action menu is displayed correctly now.
=> [android] Fix bug 51991

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCommonFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsMyFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsProjectsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsShareFragment.kt
Fix loading of files after entering in folder
=> [android] Fix files loading

app_manager/appmanager/src/main/java/app/editors/manager/managers/receivers/DownloadReceiver.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/works/DownloadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt
Added error snackbar to failed archiving during download
=> [androd][appmanager] Fixed bug #48596

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/onboarding/OnBoardingPagerFragment.kt
Fix indicator in the OnBoarding fragment
=> [android] Fix ViewPager indicator

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCloudFragment.kt
Fix bug when rotate the device counter of selected files were reset.
=> [android] Fix bug 52404

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/GlideUtils.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/models/ui/ShareUi.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/models/ui/UserUi.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/AddPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/share/AddView.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/share/SettingsView.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/ShareAdapter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/base/BaseViewTypeAdapter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/diffutilscallback/ShareSearchDiffUtilsCallback.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/ShareAddItemViewHolder.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/ShareItemViewHolder.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/base/ListFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddSearchFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/SettingsFragment.kt, app_manager/appmanager/src/main/res/layout/fragment_share_add_list.xml, app_manager/appmanager/src/main/res/layout/fragment_share_add_list_search.xml
Fixed bugs on screens of sharing
=> [android] Fix screens of sharing

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt
Fixed bug when the camera did not work correctly after asking for permission
=> [android] Fix bug 52572

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.kt
Filter is replaced from "start with" by "contains" and not case-insensitive now
=> [android] Fix bug 52543

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
If select only one file in selection mode downloading one file instead of archive now
=> [android] Fixed bug #52702

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/EnterpriseCreateLoginPresenter.kt
Fixed infinite progress bar when creating a portal
=> [android] Fix bug 52705

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/login/AccountsPresenter.kt
The login window on the bottom sheet was opened twice
=> [android] Fix bug 52804

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt
Fixed double tap in the "Recent" section
=> [android] Fix bug 52220

app_manager/appmanager/src/main/java/app/editors/manager/mvp/models/ui/GroupUi.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/AddPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddPagerFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddSearchFragment.kt, app_manager/appmanager/src/main/res/drawable/drawable_menu_search.xml, app_manager/appmanager/src/main/res/menu/share_add.xml, app_manager/appmanager/src/main/res/values/translatable.xml
Now it's possible to select all users and groups also select Admin and Everyone groups for sharing
=> [android] Fix bug 38407

app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/UploadFileViewHolder.kt
Fixed bug when upload file progress was not displayed correctly
=> [android] Fix upload file progress

app_manager/appmanager/src/main/res/values/strings.xml
Add user agent for sign in with Google for Dropbox
=> [appmanager] Fix sign in with Google

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt
Fixed snackbar informing that the external link has been copied to the clipboard
=> [android] Fix bug 51998

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/SettingsFragment.kt, app_manager/core/src/main/java/app/documents/core/network/models/share/request/RequestExternalAccess.kt, app_manager/core/src/main/java/app/documents/core/share/ShareService.kt
Added access by an external link on the personal portal
=> [android] Fix bug 53679

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt
App is crashed when rotating the screen when logging in via bottom sheet
=> [android] Fix bug 53852

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/AccountContextDialog.kt
Fixed an app crashing when opening account profile without a token
=> [android] Fix bug 53851

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt
Local folder of application is not appear when get search with "o" value
=> [appmanager] #Fix bug #53822

app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/login/SignInActivity.kt
Back button in password recovery fragment returns on previous screen now
=> [appmanager] #Fix bug #53823

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt
Fixed uploading of local files to the portal
=> [android] Fix bug 53847

app_manager/appmanager/src/main/java/app/editors/manager/dropbox/managers/providers/DropboxFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/dropbox/managers/works/DownloadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/dropbox/mvp/presenters/DocsDropboxPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/BaseFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/CloudFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/WebDavFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/managers/receivers/DownloadReceiver.java, app_manager/appmanager/src/main/java/app/editors/manager/managers/works/DownloadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsBaseView.java, app_manager/appmanager/src/main/java/app/editors/manager/onedrive/managers/providers/OneDriveFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/onedrive/managers/works/DownloadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/onedrive/mvp/presenters/DocsOneDrivePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/ActivitiesUtils.kt
Downloading continue after relaunch application
=> [appmanager] Fix bug #53835

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ActionBottomDialog.kt
Fixed the connect third-party storage in action bottom dialog
=> [android] Fix bug 53842

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ActionBottomDialog.kt
Fixed the "Upload file" in action bottom dialog
=> [android] Fix bug 53841

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/UiUtils.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/BottomAccountAdapter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/CloudAccountAdapter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/AccountContextDialog.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/custom/MainToolbar.kt
Loading avatars for Dropbox is correct now
=> Fix bug 53920

app_manager/appmanager/src/main/AndroidManifest.xml
Change orientation when logging in other storage is not interrupt logging in
=> [android][appmanager] Fix bug #53921

app_manager/appmanager/src/main/java/app/editors/manager/onedrive/mvp/presenters/OneDriveSingInPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/onedrive/mvp/views/OneDriveSignInView.kt, app_manager/appmanager/src/main/java/app/editors/manager/onedrive/ui/fragments/OneDriveSignInFragment.kt
Progress bar in OneDrive sign in process is appearing now
=> [android][appmanager] Add progress bar in OneDrive sign in process

app_manager/appmanager/src/main/java/app/editors/manager/mvp/models/explorer/Explorer.java
Submit search query on local device works properly now
=> [android][apmanager] Fix bug #53966

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/GlideUtils.kt
Fixed avatars loading in the sharing settings
=> [android] Fix bug 53927

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt
=> [android] Fix bug 54099

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt
Search for folder on device is working correct now
=> [android][appmanager] Fix bug #54100

app_manager/appmanager/src/main/java/app/editors/manager/dropbox/mvp/presenters/DocsDropboxPresenter.kt
Downloading a few files and folders is working correct now
=> [android][appmanager] Fix multiple downloading for Dropbox

app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/main/PasscodeActivity.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/activities/main/PasscodeActivityCompose.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/base/BaseViews.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/fragments/main/PasscodeFragmentCompose.kt
App top bar was added in Passcode Lock Screen according to layout
=> [android][appmanager] Fix bug #54158

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/ShareItemViewHolder.kt, app_manager/appmanager/src/main/res/layout/list_share_settings_item.xml
Showing the folder/cloud storage owner in the sharing settings
=> [android] Fix bug 51731

app_manager/appmanager/src/main/java/app/editors/manager/managers/works/UploadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt
Error while upload handles correctly
=> [android][appmanager] Upload error handle if request is bad

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Tap on search icon doesn't log out from personal
=> [android][appmanager] Fix bug #54314

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Change orientation while searching works correctly now
=> [android][appmanager] Fix bug #54325

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Search is looking for items only in section where was opened now
=> [android][appmanager] Fix searching for section

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Excess searching result were removed from list
=> [android][appmanager] Fix searching redundancy

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsOnDeviceView.java, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt
Showing portals if user is not logged in when uploading a file on the portal
=> [android] Fix bug 53922

toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/UiUtils.kt
When renaming a sheet name, the value cannot be empty
=> [android][editors] Fix bug 53840

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt
The search bar was not cleared properly
=> [android] Fix bug 54448

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt
NPE after changing orientation during removing files in local section
=> [android][appmanager] Fix bug #54493

app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/fragments/main/PasscodeFragmentCompose.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/fragments/main/PasscodeOperationFragmentCompose.kt, toolkit/libtoolkit/src/main/res/values/dimens.xml
Change text size on switch item in Passcode Lock screen
=> [android][appmanager] Fix bug #54505

app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/fragments/main/PasscodeOperationFragmentCompose.kt
Correct color for subtitle in night theme for Passcode lock screens
=> [android][appmanager] Fix bug #54515

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/CloudAccountFragment.kt
Enter passcode during changing accounts is not required
=> [android][appmanager] Fix bug #54514

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/MainActivityPresenter.kt
File from Projects is opened when the same account is logged in but offline
=> [android][appmanager] Fix bug #54559

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/ProfilePresenter.kt
Open profile screen set correct state for Dropbox and OneDrive
=> [android][appmanager] Fix bug #54620

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/ProfilePresenter.kt
Update account info is correct now
=> [android][appmanager] Fix bug #54621

app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/fragments/main/PasscodeOperationFragmentCompose.kt
Subtitle and error text in passcode screen align to center
=> [android][appmanager] Fix bug #54699

app_manager/core/src/main/java/app/documents/core/network/models/login/User.kt
Fixed bug in the sharing settings when the user's email is null
=> [android] Fix bug 54750

app_manager/appmanager/src/main/AndroidManifest.xml
Changing orientation while connecting to dropbox/onedrive works correctly
=> [android][appmanager] Fix bug #54792

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/ProfilePresenter.kt
Base url updates when profile fragment is opened
=> [android][appmanager] Fix base url in profile fragment

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddPagerFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/share/AddSearchFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/custom/SharePanelViews.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/popup/SharePopup.kt
Fixed access rights in the share panel popup
=> [android] Fix bug 54751

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.java
Local and cloud searches work more stable with empty search bar and incorrect request
=> [android][appmanager] Fix bug #54790

app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/FileViewHolder.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/FolderViewHolder.kt
Fixed icon mask display after deselection
=> [android] Fix bug 54818

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/MainActivityPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/MainPagerPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/MainActivityView.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/MainPagerView.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/main/MainActivity.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/MainPagerFragment.kt, app_manager/appmanager/src/main/res/values/translatable.xml
Replace snackbar when try to open file from "Projects" with more informative snackbar with "Switch account" action
=> [android][appmanager] Fix bug #54564

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsProjectsFragment.kt
Hide snackbar if user doesn't have access to Project section
=> [android][appmanager] Fix bug #54989

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/AddPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt
Fixed the able of changing access rights of the document owner
=> [android] Fix bug 55490

app_manager/appmanager/build.gradle.kts, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/base/BasePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/MainPagerFragment.kt
Fixed error handling after opening app on blocked account
=> [android] Fix bug 55554

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt
Explorer sorting in filtering mode in local section works correctly
=> [android][appmanager] Fix bug #55594

app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/main/MainActivity.kt
Fixed FAB display after cloud selection
=> [android] Fix bug 55666

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/login/EnterpriseSignInFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/login/PersonalPortalFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/custom/SocialViews.kt, app_manager/appmanager/src/main/res/values/translatable.xml
Changed a snackbar when authorization has been cancelled
=> [android] Fix bug 55598

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/StringUtils.kt
=> [android] Fix bug 55545

app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/mvp/models/explorer/DriveItemValue.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/mvp/presenters/DocsOneDrivePresenter.kt
Model for OneDrive items was fixed
=> [android][appmanager] Fix bug #56170

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt
Fixed "Connection error" when trying to delete a file in kDrive
=> [android] Fix bug 55434

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt
Files are added in recent list after creating
=> [android][appmanager] Fix bug #46896

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/MainPagerPresenter.kt
Fixed adding/removing favorites in the context menu
=> [android] Fix bug 56549

app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/holders/FileViewHolder.kt
Displaying name of file creator was fixed
=> [android][appmanager] Fix bug #56550

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/StorageUtils.java, app_manager/appmanager/src/main/java/app/editors/manager/storages/base/fragment/BaseStorageSignInFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/dropbox/ui/fragments/DropboxSignInFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/ui/fragments/GoogleDriveSignInFragment.kt
Error during adding Dropbox and Google Drive as third party storage on portal was fixed
=> [android][appmanager] Fix bug #56558

toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/KeyboardUtils.kt
=> [android] Fix bug 56597

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsRecentView.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/RecentAdapter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/adapters/base/BaseViewTypeAdapter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt
=> [android] Fix bug 56551

app_manager/appmanager/src/main/java/app/editors/manager/storages/base/work/BaseStorageUploadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/managers/works/UploadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/managers/works/UploadWork.kt
Uploading files for OneDrive and Google Drive works correctly
=> [android][appmanager] Fix bug #56553

app_manager/appmanager/src/main/java/app/editors/manager/managers/works/UploadWork.kt
Uploading files on Personal correct now
=> [android][appmanager] Fix bug #56657

app_manager/appmanager/src/main/java/app/editors/manager/mvp/models/models/OpenDataModel.kt
Opening files from Projects was fixed
=> [android][appmanager] Fix bug #51481

app_manager/appmanager/src/main/java/app/editors/manager/storages/base/fragment/BaseStorageDocsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/dropbox/mvp/presenters/DocsDropboxPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/dropbox/ui/fragments/DocsDropboxFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/managers/works/UploadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/mvp/presenters/DocsGoogleDrivePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/ui/fragments/DocsGoogleDriveFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/managers/works/UploadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/mvp/presenters/DocsOneDrivePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/ui/fragments/DocsOneDriveFragment.kt
Uploading photos from camera and opening images for storages were fixed
=> [android][appmanager] Fix bug #56754

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt
Requesting permission is extended for On Device during import
=> [android][appmanager] Fix bug #56894

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.kt
Option "Upload to portal" in local section was hidden for OneDrive, Dropbox and GoogleDrive temporary
=> [android][appmanager] Fix "Upload to My" for storages

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/BiometricsUtils.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/compose/fragments/main/PasscodeOperationFragmentCompose.kt
Visibility of biometric button on Passcode screen is depended on hardware opportunities of device, existence of fingerprints
=> [android][appmanager] Fix bug #56997

app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/managers/providers/GoogleDriveFileProvider.kt
Cast empty string to long is corrected
=> [android][appmanager] Fix cast empty string to long

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt, app_manager/appmanager/src/main/res/values/translatable.xml
Permission error snackbar was added when local import fails due to access denied
=> Permission error snack

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCloudFragment.kt, app_manager/appmanager/src/main/res/layout/list_share_settings_item.xml
Fixed change of external link access
=> [android] Fix bug 57553

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/MainPagerFragment.kt
Fixed after interrupting the active connection, trash does not appeared
=> [android] Fix bug 57741

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/ContextBottomDialog.kt
Removed uploading on the portal as a guest
=> [android] Fix bug 57785

app_manager/appmanager/src/main/res/menu/docs_main.xml
Fixed the main menu in vertical orientation
=> [android] Fix bug 58173

app_manager/appmanager/src/main/res/menu-land/docs_main.xml
Fixed main menu in landscape orientation
=> [android] Fix bug 58172

app_manager/appmanager/src/main/java/app/editors/manager/storages/base/view/DocsGoogleDriveView.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/googledrive/api/GoogleDriveService.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/googledrive/api/GoogleDriveServiceProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/googledrive/api/IGoogleDriveServiceProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/managers/providers/GoogleDriveFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/mvp/models/GoogleDriveCloudFile.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/mvp/presenters/DocsGoogleDrivePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/ui/fragments/DocsGoogleDriveFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/ui/fragments/operations/DocsGoogleDriveOperationFragment.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/tools/LocalContentTools.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/FileUtils.kt
Fixed opening a document in Google Drive storage
=> [android] Fix bug 58104

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsBaseView.java, app_manager/appmanager/src/main/java/app/editors/manager/storages/base/fragment/BaseStorageDocsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/base/fragment/BaseStorageOperationsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCommonFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsFavoritesFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsMyFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsProjectsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsShareFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsTrashFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsWebDavFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/operations/DocsCloudOperationFragment.kt
Fixed update of adding/deleting from favorites
=> [android] Fix bug 58164

app_manager/appmanager/src/main/java/app/editors/manager/storages/base/fragment/BaseStorageDocsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/ui/fragments/DocsGoogleDriveFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/onedrive/ui/fragments/DocsOneDriveFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsCloudFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsWebDavFragment.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/popup/ActionBarPopup.kt
Fixed the location of the action popup menu
=> [android] Fix bug 58235

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/storages/googledrive/ui/fragments/DocsGoogleDriveFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/activities/base/BaseActivity.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/dialogs/common/holders/EditLineHolder.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/ui/fragments/base/BaseFragment.kt, toolkit/libtoolkit/src/main/res/layout/dialog_fragment_edit_line_hint.xml
Fixed extension location when adding/renaming a document
=> [android] Fix bug 58142

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/LocalFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt
Fixed sorting of documents on device
=> [android] Fix bug 58163

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsTrashFragment.kt
Fixed display of the trash icon in menu
=> [android] Fix bug 58167

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/MainActivityPresenter.kt
Fixed resetting the filter after closing the application
=> [android] Fix bug 58170

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/filter/FilterFragment.kt
Added filter/search with subfolders for portals
=> [android] Add filter/search with subfolders

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/filter/FilterPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt
Fixed the display of filtered files by type
=> [android] Fix bug 58234

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.kt
Fixed updating the recent list when clicked
=> [android] Fix bug 58226

toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/tools/GlideTool.kt, toolkit/libtoolkit/src/main/res/values-night/colors.xml, toolkit/libtoolkit/src/main/res/values/colors.xml
Refactoring of property objects screens
=> [android][editors] Refactor property screens

toolkit/libtoolkit/src/main/res/values-sw720dp/styles.xml
Fixed background color of dialog on tablets
=> [android] Fix bug 58151

app_manager/appmanager/src/main/AndroidManifest.xml
Fixed blank screen after exiting Clouds
=> [android] Fix bug 59125

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsRecentPresenter.kt
Fixed uploading a webdav file from a recent
=> [android] Fix bug 56456

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt
Fixed the display of search results with subfolders
=> [android] Fix bug 58169

app_manager/appmanager/src/main/java/app/editors/manager/managers/providers/CloudFileProvider.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/filter/RoomFilterPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/filter/RoomFilterFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRoomFragment.kt
=> [android] Fix bug 60197

app_manager/appmanager/src/main/java/app/editors/manager/ui/activities/base/BaseAppActivity.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/AppSettingsFragment.kt, app_manager/appmanager/src/main/res/values-bg/translatable.xml, app_manager/appmanager/src/main/res/values-cs/translatable.xml, app_manager/appmanager/src/main/res/values-de/translatable.xml, app_manager/appmanager/src/main/res/values-es/translatable.xml, app_manager/appmanager/src/main/res/values-fr/translatable.xml, app_manager/appmanager/src/main/res/values-it/translatable.xml, app_manager/appmanager/src/main/res/values-lo/translatable.xml, app_manager/appmanager/src/main/res/values-pl/translatable.xml, app_manager/appmanager/src/main/res/values-pt-rBR/translatable.xml, app_manager/appmanager/src/main/res/values-ru/translatable.xml, app_manager/appmanager/src/main/res/values-zh/translatable.xml, app_manager/appmanager/src/main/res/values/translatable.xml, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/ActivitiesUtils.kt, toolkit/libtoolkit/src/main/res/values-bg/translatable.xml, toolkit/libtoolkit/src/main/res/values-cs/translatable.xml, toolkit/libtoolkit/src/main/res/values-de/translatable.xml, toolkit/libtoolkit/src/main/res/values-es/translatable.xml, toolkit/libtoolkit/src/main/res/values-fr/translatable.xml, toolkit/libtoolkit/src/main/res/values-it/translatable.xml, toolkit/libtoolkit/src/main/res/values-lo/translatable.xml, toolkit/libtoolkit/src/main/res/values-pl/translatable.xml, toolkit/libtoolkit/src/main/res/values-pt-rBR/translatable.xml, toolkit/libtoolkit/src/main/res/values-ru/translatable.xml, toolkit/libtoolkit/src/main/res/values-zh/translatable.xml, toolkit/libtoolkit/src/main/res/values/strings.xml, toolkit/libtoolkit/src/main/res/values/translatable.xml
Moved the feedback strings to toolkit for share them with editors
=> [android] Move feedback strings to toolkit

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/views/popup/SharePopup.kt, app_manager/core/src/main/java/app/documents/core/network/models/share/response/ResponseRoomShare.kt, app_manager/core/src/main/java/app/documents/core/share/ShareService.kt
Fixed a changing type of shared access of room members
=> [android] Fix bug 60436

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/filter/BaseFilterFragment.kt
Fixed filtering on personal portal
=> [android] Fix bug 60820

app_manager/appmanager/src/main/java/app/editors/manager/managers/utils/UiUtils.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsCloudPresenter.kt
=> [android] Fix bug 60521

app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt
Fixed copy/move of selected files
=> [android] Fix bug 60871

toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/FragmentUtils.kt
=> [android][editors] Fix bug 59916

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt, toolkit/libtoolkit/src/main/java/lib/toolkit/base/managers/utils/EditorsContract.kt
Fixed opening in edit mode in native editors
=> [android] Fix bug 62685

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsOnDevicePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsBaseView.java, app_manager/appmanager/src/main/java/app/editors/manager/mvp/views/main/DocsOnDeviceView.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsOnDeviceFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsTrashFragment.kt, app_manager/appmanager/src/main/res/values/translatable.xml
Fixed the snack bar message after deleting items
=> [android] Fix bug 62843

app_manager/appmanager/src/main/java/app/editors/manager/managers/works/WebDavDownloadWork.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsBasePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/main/DocsWebDavPresenter.kt
=> [android] Fix bug 64312

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/explorer/ExplorerContextItemVisible.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/base/BaseStorageDocsFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/core/src/main/java/app/documents/core/network/common/contracts/ApiContract.kt
Fixed showing favourite in context menu and opening by edit button on webdav section
=> [android] Fix bug 64311

app_manager/appmanager/src/main/java/app/editors/manager/ui/views/popup/SharePopup.kt
Fixed the viewer access type for custom room
=> [android] Fix bug 64354

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/explorer/ExplorerContextItemVisible.kt
Fixed the restore button in archive context menu
=> [android] Fix bug 60855

app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/share/SettingsPresenter.kt, app_manager/core/src/main/java/app/documents/core/network/common/models/BaseResponse.kt, app_manager/core/src/main/java/app/documents/core/network/share/ShareService.kt
Fixed the sharing in personal portal
=> [android] Fix bug 55322

app_manager/appmanager/src/main/java/app/editors/manager/ui/dialogs/explorer/ExplorerContextState.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsRecentFragment.kt
Fixed app crash when serializing context menu state
=> [android] Fix context menu serialization

app_manager/appmanager/src/main/java/app/editors/manager/managers/tools/ActionMenuFactory.kt, app_manager/appmanager/src/main/java/app/editors/manager/mvp/presenters/storages/DocsOneDrivePresenter.kt, app_manager/appmanager/src/main/java/app/editors/manager/ui/fragments/main/DocsBaseFragment.kt, app_manager/core/src/main/java/app/documents/core/providers/OneDriveFileProvider.kt
Removed unsupported order values
=> [android] Fix bug 68698
